# Generated by Django 5.2 on 2025-08-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectionalizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('FV', 'FV'), ('FVC', 'FVC'), ('B', 'B'), ('BC', 'BC'), ('Q', 'Q'), ('QC', 'QC'), ('A', 'A'), ('AC', 'AC'), ('AV', 'AV'), ('AVC', 'AVC')], max_length=4)),
                ('num', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TransformationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=7, unique=True)),
                ('prefix', models.CharField(choices=[('CT', 'CT'), ('PT', 'PT')], default='CT', max_length=2)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rem_ctrl', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('NIVEL', 'A nivel'), ('SUBT', 'Subterránea'), ('POZO', 'Pozo'), ('PLAT', 'Plataforma')], max_length=5)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_centers', models.ManyToManyField(blank=True, related_name='source_centers', to='grid.transformationcenter', verbose_name='Centros de transformación conectados')),
                ('connected_sectionalizers', models.ManyToManyField(blank=True, related_name='connected_to_centers', to='grid.sectionalizer', verbose_name='Sectionalizers conectados')),
            ],
        ),
    ]
