# Generated by Django 5.2 on 2025-08-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sectionalizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('FV', 'FV'), ('FVC', 'FVC'), ('B', 'B'), ('BC', 'BC'), ('Q', 'Q'), ('QC', 'QC'), ('A', 'A'), ('AC', 'AC'), ('AV', 'AV'), ('AVC', 'AVC')], max_length=4)),
                ('num', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='grid.sectionalizer')),
            ],
        ),
        migrations.CreateModel(
            name='TransformationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rem_ctrl', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('NIVEL', 'A nivel'), ('SUBT', 'Subterránea'), ('POZO', 'Pozo')], max_length=5)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_centers', models.ManyToManyField(blank=True, related_name='source_centers', to='grid.transformationcenter', verbose_name='Centros de transformación conectados')),
                ('connected_sectionalizers', models.ManyToManyField(blank=True, related_name='connected_to_centers', to='grid.sectionalizer', verbose_name='Sectionalizers conectados')),
            ],
        ),
        migrations.AddField(
            model_name='sectionalizer',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.transformationcenter'),
        ),
    ]
