# Generated by Django 5.2 on 2025-08-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformationcenter',
            name='prefix',
            field=models.CharField(choices=[('CT', 'CT'), ('PT', 'PT')], default='CT', max_length=2),
        ),
    ]
