# Generated by Django 5.2 on 2025-08-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_transformationcenter_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformationcenter',
            name='type',
            field=models.CharField(choices=[('NIVEL', 'A nivel'), ('SUBT', 'Subterránea'), ('POZO', 'Pozo'), ('PLAT', 'Plataforma')], max_length=5),
        ),
    ]
