version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tp5_db
      POSTGRES_USER: tp5_user
      POSTGRES_PASSWORD: tp5_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: alvitedamian/tp5-backend:1.0
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: tp5_db
      POSTGRES_USER: tp5_user
      POSTGRES_PASSWORD: tp5_pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  frontend:
    image: alvitedamian/tp5-frontend:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
